<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{e3bb108d-9a15-4605-b94f-cc9939549109}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Tc3_Motion.WareHousingExample_Tc3_DriveMotionControl();

WareHousingExample_Tc3_DriveMotionControl();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>